csv_upload_form:
    path: /upload
    methods: [GET]
    defaults:
        _controller: AppBundle:CSV:uploadForm

csv_upload_process:
    path: /upload
    methods: [POST]
    defaults:
        _controller: AppBundle:CSV:uploadProcess
