AppBundle\Entity\Decksideslot:
    type: entity
    table: decksideslot
    manyToOne:
        deck:
            targetEntity: Deck
            nullable: false
            inversedBy: sideslots
            joinColumn:
                name: deck_id
                referencedColumnName: id
        card:
            targetEntity: Card
            nullable: false
            joinColumn:
                name: card_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        quantity:
            type: smallint
