AppBundle\Entity\Decklistsideslot:
    type: entity
    table: decklistsideslot
    manyToOne:
        decklist:
            targetEntity: Decklist
            nullable: false
            inversedBy: sideslots
            joinColumn:
                name: decklist_id
                referencedColumnName: id
        card:
            targetEntity: Card
            nullable: false
            joinColumn:
                name: card_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        quantity:
            type: smallint
