AppBundle\Entity\Questlog:
    type: entity
    table: questlog
    manyToOne:
        user:
            targetEntity: User
            nullable: false
            inversedBy: questlogs
            joinColumn:
                name: user_id
                referencedColumnName: id
        scenario:
            targetEntity: Scenario
            nullable: false
            inversedBy: questlogs
            joinColumn:
                name: scenario_id
                referencedColumnName: id
    oneToMany:
        decks:
            targetEntity: QuestlogDeck
            mappedBy: questlog
            cascade: ["persist","remove"]
        comments:
            targetEntity: QuestlogComment
            orderBy: { 'dateCreation': 'ASC' }
            mappedBy: questlog
            cascade: ["persist","remove"]
    manyToMany:
        favorites:
            targetEntity: User
            inversedBy: questlog_favorites
            joinTable:
                name: questlog_favorite
                cascade: ["persist","remove"]
                joinColumns:
                    fellowship_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
        votes:
            targetEntity: User
            inversedBy: questlog_votes
            joinTable:
                name: questlog_vote
                cascade: ["persist","remove"]
                joinColumns:
                    fellowship_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        nameCanonical:
            type: string
            length: 255
            column: name_canonical
        descriptionMd:
            type: text
            nullable: true
            column: description_md
        descriptionHtml:
            type: text
            nullable: true
            column: description_html
        datePlayed:
            type: datetime
            nullable: false
            column: date_played
        questMode:
            type: string
            length: 32
            column: quest_mode
        success:
            type: boolean
            nullable: false
        score:
            type: smallint
            nullable: true
        nbDecks:
            type: integer
            column: nb_decks
        nbVotes:
            type: integer
            column: nb_votes
        nbFavorites:
            type: integer
            column: nb_favorites
        nbComments:
            type: integer
            column: nb_comments
        isPublic:
            type: boolean
            nullable: false
            column: is_public
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        datePublish:
            type: datetime
            nullable: true
            column: date_publish
