AppBundle\Entity\QuestlogComment:
    type: entity
    table: questlog_comment
    manyToOne:
        user:
            targetEntity: User
            nullable: false
            inversedBy: questlog_comments
            joinColumn:
                name: user_id
                referencedColumnName: id
        questlog:
            targetEntity: Questlog
            nullable: false
            inversedBy: comments
            joinColumn:
                name: questlog_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        text:
            type: text
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        isHidden:
            type: boolean
            column: is_hidden

