AppBundle\Entity\Sphere:
    type: entity
    table: sphere
    oneToMany:
        cards:
            targetEntity: Card
            orderBy: {'position':'ASC'}
            mappedBy: sphere
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
        is_primary:
            type: boolean
            nullable: false
        octgnid:
            type: string
            nullable: true
